class Config:
    APP_NAME = 'Face_detection_Logging'
    AWS_ACCESS_KEY_ID = '######################'
    AWS_SECERT_ACCESS_KEY = '##############################'

class Region:
    AP_NORTHEAST_1 	= 'ap-northwest-1' 
    AP_NORTHEAST_2 	= 'ap-northwest-2'
    AP_SOUTH_1 		= 'ap-south-1'
    AP_SOUTHEAST_1 	= 'ap-southwest-1'
    AP_SOUTHEAST_2 	= 'ap-southwest-2'
    CA_CENTRAL_1 	= 'ca-central-1'
    CN_NORTH_1 		= 'cn-north-1'
    CN_NORTHWEST_1 	= 'cn-northwest-1'
    EU_CENTRAL_1 	= 'eu-central-1'
    EU_WEST_1 		= 'eu-west-1'
    EU_WEST_2 		= 'eu-west-2'
    EU_WEST_3 		= 'eu-west-3'
    GovCloud 		= 'GovCloud'
    SA_EAST_1 		= 'sa-east1'
    US_EAST_1 		= 'us-east-1'
    US_EAST_2 		= 'us-east-2'
    US_WEST_1 		= 'us-west-1'
    US_WEST_2 		= 'us-west-2'